/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _mainLayoutRouteImport } from './routes/__mainLayout'
import { Route as _mainLayoutIndexRouteImport } from './routes/__mainLayout/index'
import { Route as _mainLayoutRosterRouteImport } from './routes/__mainLayout/roster'

const _mainLayoutRoute = _mainLayoutRouteImport.update({
  id: '/__mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const _mainLayoutIndexRoute = _mainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutRosterRoute = _mainLayoutRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => _mainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _mainLayoutIndexRoute
  '/roster': typeof _mainLayoutRosterRoute
}
export interface FileRoutesByTo {
  '/roster': typeof _mainLayoutRosterRoute
  '/': typeof _mainLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__mainLayout': typeof _mainLayoutRouteWithChildren
  '/__mainLayout/roster': typeof _mainLayoutRosterRoute
  '/__mainLayout/': typeof _mainLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/roster'
  fileRoutesByTo: FileRoutesByTo
  to: '/roster' | '/'
  id: '__root__' | '/__mainLayout' | '/__mainLayout/roster' | '/__mainLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _mainLayoutRoute: typeof _mainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__mainLayout': {
      id: '/__mainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _mainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__mainLayout/': {
      id: '/__mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _mainLayoutIndexRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/roster': {
      id: '/__mainLayout/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof _mainLayoutRosterRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
  }
}

interface _mainLayoutRouteChildren {
  _mainLayoutRosterRoute: typeof _mainLayoutRosterRoute
  _mainLayoutIndexRoute: typeof _mainLayoutIndexRoute
}

const _mainLayoutRouteChildren: _mainLayoutRouteChildren = {
  _mainLayoutRosterRoute: _mainLayoutRosterRoute,
  _mainLayoutIndexRoute: _mainLayoutIndexRoute,
}

const _mainLayoutRouteWithChildren = _mainLayoutRoute._addFileChildren(
  _mainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _mainLayoutRoute: _mainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
